# BAIXA UMA VERSÃO ALPINE DO LINUX, BEM PEQUENA E O NODE NA VERSÃO 18
FROM node:16-alpine
# DEFINE ONDE SERÁ O DIRETÓRIO DO NOSSO APP
WORKDIR /usr/src/app

# COPIA O PACKAGE.JSON PARA O NOSSO WORKDIR
COPY package*.json ./

# INSTALA AS DEPENDCIAS E LIMPA O CACHE PARA DEIXAR IMAGEM MENOR
RUN npm install --only=prod && npm cache clean --force

# COPIA TODOS ARQUIVOS DA RAIZ PARA NOSSO WORKDIR
COPY . .

# CONFIGURA A PORTA 3000 DA NOSSA APLICAÇÃO
EXPOSE 3000

# TRUQUE PARA NÃO RODAR O NPM RUN DEV OU START PARA DEPENDE DO DB LÁ NO DOCKER-COMPOSE
CMD ["tail", "-f", "/dev/null"] 
